version: "3"

services:
# =============== MASTER =================
  hdfs-namenode:
    image: kevinity310/hadoop-namenode:dev
    container_name: hdfs-namenode
    restart: always
    ports:
      - 9870:9870
      - 9010:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
    env_file:
      - ./hadoop-port-dev.env

  hdfs-datanode:
    image: kevinity310/hadoop-datanode:dev
    container_name: hdfs-datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "hdfs-namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://hdfs-namenode:9000
    ports:
      - "9864:9864"
    env_file:
      - ./hadoop-port-dev.env

  yarn-resourcemanager:
    image: kevinity310/hadoop-resourcemanager:dev
    container_name: yarn-resourcemanager
    ports:
      - "8088:8088"
    restart: always
    environment:
      SERVICE_PRECONDITION: "hdfs-namenode:9000 hdfs-namenode:9870 hdfs-datanode:9864"
    env_file:
      - ./hadoop-port-dev.env
      
  yarn-historyserver:
    image: kevinity310/hadoop-historyserver:dev
    container_name: historyserver
    restart: always
    ports:
      - "8188:8188"
    environment:
      SERVICE_PRECONDITION: "hdfs-namenode:9000 hdfs-namenode:9870 hdfs-datanode:9864 yarn-resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop-port-dev.env

  hive-server:
    image: kevinity310/hive-server:dev
    dockerfile: ./hive-server/Dockerfile
    container_name: hive-server
    env_file:
      - ./hadoop-port-dev.env

  # hive-metastore:
  #   image: bde2020/hive:2.3.2-postgresql-metastore
  #   container_name: hive-metastore
  #   env_file:
  #     - ./hadoop-port-dev.env
  #   command: /opt/hive/bin/hive --service metastore
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
  #   ports:
  #     - "9083:9083"

  # hive-metastore-postgresql:
  #   image: bde2020/hive-metastore-postgresql:2.3.0
  #   container_name: hive-metastore-postgresql

  # presto-coordinator:
  #   image: shawnzhu/prestodb:0.181
  #   container_name: presto-coordinator
  #   ports:
  #     - "8089:8089"

# =============== EDGE =================

  jupyter_dev:
    image: kevinity310/jupyter-notebook:dev
    container_name: jupyter_dev
    ports:
      - "8889:8888"
    env_file:
      - ./hadoop-port-dev.env

# =============== WORKER =================

  yarn-nodemanager:
    image: kevinity310/hadoop-nodemanager:dev
    container_name: yarn-nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "hdfs-namenode:9000 hdfs-namenode:9870 hdfs-datanode:9864 yarn-resourcemanager:8088"
    env_file:
      - ./hadoop-port-dev.env
      
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

